baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Ciro Lucio Tecce"
theme = 'LoveIt'

[params]
  [params.header.title]
    name = "Ciro Lucio Tecce"
  [params.home]
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "https://media.licdn.com/dms/image/C4D03AQHa5_BCYbOLFA/profile-displayphoto-shrink_800_800/0/1630404291817?e=1691020800&v=beta&t=fD4rXcfjMrsKJ9Lx9Hv8mS6diZIonC_a3nAE7iwYNaE"
      # title shown in home page (HTML format is supported)
      title = "Ciro Lucio Tecce"
      # subtitle shown in home page (HTML format is supported)
      subtitle = "During my studies, I learned that no matter the subject, the field nor the dimension of the problem, just the possibility to face new challenges is important to me. I am trying to let my career be led by this awareness, looking for the opportunity to test my capabilities and skills in challenging and rapidly evolving scenarios. I am conscious that I have to study, learn and experience so much before becoming the person I would like to be, but this does not scare me, quite the opposite, it is pushing me further to go beyond my limits."
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = ""
  [params.social]
    GitHub = "Cirius1792"
    Linkedin = "ciro-lucio-tecce-3bb628175/"
    Instagram = "clt92/"
    Steam = ""
    Googlescholar = ""
    Email = "cirolucio.tecce@gmail.com"
